version: '3.3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
      - redis
  scheduler:
    image: digitalocean.com/php
    container_name: scheduler
    depends_on:
      - app
    volumes:
      - .:/var/www/
    environment:
      CONTAINER_ROLE: scheduler

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "88:80"
      - "445:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  #Redis
  redis:
    image: redis:5-alpine
    restart: always
    container_name: redis
    ports:
      - 6385:6379

  #MySQL Service
  db:
    image: postgres
    ports:
      - "6543:5432"
    volumes:
      - postgres-data-12:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
  adminer:
    image: adminer
    ports:
      - "8089:8080"
    restart: unless-stopped
    depends_on:
      - db

#Docker Networks

#Volumes
volumes:
  postgres-data-12:



